# Generated by Django 2.1.4 on 2019-09-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190902_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='分类名称')),
                ('topic_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='t_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='t_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='t_type',
        ),
        migrations.AddField(
            model_name='topic',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='responce_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='view_times',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TopicType',
        ),
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.Column'),
        ),
    ]
